golang: Workaround Cython 3 crash on `typeid(...[0])`
While Cython 0.29.x works ok on e.g. the following

    cdef const type_info* typ = &typeid(pyerr.err._ptr()[0])

Cython 3 started to crash on that with

      File "/home/kirr/tmp/trashme/pyexc/1.venv/lib/python3.12/site-packages/Cython/Compiler/ExprNodes.py", line 1523, in calculate_result_code
        return self.result_code
    AttributeError: 'IntNode' object has no attribute 'result_code'. Did you mean: 'result_ctype'?

I filed the bug into https://github.com/cython/cython/issues/7069 and
the fix is there at https://github.com/cython/cython/pull/7070 but
upstream said there will likely be no 3.0.x Cython release anymore.

-> Workaround this ICE via using our own xtypeid function instead of
typeid operator. The workaround works ok on both Cython 0.29.x and
Cython 3.

/reviewed-by @jerome
/reviewed-on https://lab.nexedi.com/nexedi/pygolang/-/merge_requests/37