golang_str: tests: Adjust deepReplaceStr2Bytearray for py3.14
The exception message when trying to add bytearray to set was changed
which lead to deepReplaceStr2Bytearray not detecting it internally:

            # for self-referencing cases, going replace through arguments/state
            # might already replace the object itself
            if id(obj) in r.memo:
                obj_ = r.memo[id(obj)]
            else:
    >           obj_ = new(*newargv)
                       ^^^^^^^^^^^^^
    E           TypeError: cannot use 'bytearray' as a set element (unhashable type: 'bytearray')

    kirr@deca:~$ python3.13
    Python 3.13.12+ (heads/3.13-dirty:e418e3351f8, Feb 25 2026, 11:13:16) [GCC 14.2.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> s = set()
    >>> b = bytearray(b'abc')
    >>> s.add(b)
    Traceback (most recent call last):
      File "<python-input-2>", line 1, in <module>
        s.add(b)
        ~~~~~^^^
    TypeError: unhashable type: 'bytearray'

    kirr@deca:~$ python3.14
    Python 3.14.3+ (heads/3.14-dirty:0701ce636c3, Feb 25 2026, 11:10:36) [GCC 14.2.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> s = set()
    >>> b = bytearray(b'abc')
    >>> s.add(b)
    Traceback (most recent call last):
      File "<python-input-2>", line 1, in <module>
        s.add(b)
        ~~~~~^^^
    TypeError: cannot use 'bytearray' as a set element (unhashable type: 'bytearray')

-> Adjust the match criteria only to search in the exception message
   instead of comparing it exactly.

/reviewed-by @jerome
/reviewed-on https://lab.nexedi.com/nexedi/pygolang/-/merge_requests/39