setup: py.bench needs py on py3
Because recent pytest stoppped to depend on py and py.bench fails without py installed:

    (py3.venv) kirr@deca:~/src/tools/go/pygolang-master$ py.bench golang/strconv_test.py
    Traceback (most recent call last):
      File "/home/kirr/src/tools/go/py3.venv/bin/py.bench", line 5, in <module>
        from golang.cmd.pybench import main
      File "/home/kirr/src/tools/go/pygolang-master/golang/cmd/pybench.py", line 57, in <module>
        from py.process import ForkedFunc
    ModuleNotFoundError: No module named 'py.process'; 'py' is not a package

/proposed-for-review-on https://lab.nexedi.com/nexedi/pygolang/-/merge_requests/25