libgolang: random_shuffle -> shuffle
There is no std::random_shuffle on `MSVC /std:c++20` because it was removed in C++17:

    golang/runtime/libgolang.cpp(946): error C2039: 'random_shuffle': is not a member of 'std'
    z:\home\kirr\src\tools\go\pygo-win\BuildTools\vc\tools\msvc\14.35.32215\include\random(34): note: see declaration of 'std'
    golang/runtime/libgolang.cpp(946): error C3861: 'random_shuffle': identifier not found

    https://en.cppreference.com/w/cpp/algorithm/random_shuffle