golang: Fix @func(cls) environment cleanup on py3.13
On py3.13 test_func fails in its "inside another function" part as

    =================================== FAILURES ===================================
    __________________________________ test_func ___________________________________

    ...

            # also test how @func works inside another function
            # we need to test this because namespace implementations are different when
            # running as top-level module and inside a function.
            def _(l):
                m = re.match(br'^[^#]*#(.*)\s+\+funcfunc(\s+\+py3)?$', l)
                if m is not None:
                    l = m.group(1)
                    if m.group(2) and not six.PY3:
                        l = b''
                    l += b'\n'
                return l
            s = b''.join([_(l) for l in s.splitlines(True)])
    >       run(s)

    golang/golang_test.py:1000:
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
    golang/golang_test.py:984: in run
        six.exec_(c, mod.__dict__)
    golang/testprog/golang_test_func.py:165: in <module>
        ???
    golang/testprog/golang_test_func.py:164: in tmain
        ???
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    ...

            # undefined var after `@func(cls) def var` should be not set
            # same for cellvar
            assert 'var'     not in locals()
            assert 'cellvar' not in locals()
            @func(MyClass)
            def var(self, v):
                assert v == 8
                return v + 1
            @func(MyClass)
            def cellvar(self, v):
                assert v == 9
                return v + 1
            gc.collect()    # pypy needs this to trigger _DelAttrAfterMeth GC
    >       assert 'var'     not in locals()
    E       AssertionError: assert 'var' not in {'@py_assert0': 'var', '@py_assert1': None, '@py_assert2': None, '@py_assert4': None, ...}
    E        +  where {'@py_assert0': 'var', '@py_assert1': None, '@py_assert2': None, '@py_assert4': None, ...} = locals()

    =============================== warnings summary ===============================
    golang/golang_test.py::test_func
      /home/kirr/src/tools/go/py313.venv/lib/python3.13/site-packages/_pytest/unraisableexception.py:67: PytestUnraisableExceptionWarning: Exception ignored in: <function _DelAttrAfterMeth.__del__ at 0x7fa9d33f7d80>

      Traceback (most recent call last):
        File "/home/kirr/src/tools/go/pygolang-master/golang/__init__.py", line 128, in __del__
          _frame_dellocal(self.frame, self.name)
          ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
        File "golang/_golang.pyx", line 1078, in golang._golang._pyframe_dellocal
          del l[name]
      ValueError: cannot remove local variables from FrameLocalsProxy

      Enable tracemalloc to get traceback where the object was allocated.
      See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.
        warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))

What happens here is that starting from py3.13 frame.f_locals gives
FrameLocalsProxy object instead of providing dict snapshot, and that
FrameLocalsProxy explicitly rejects deletion of variables:

https://peps.python.org/pep-0667/
https://docs.python.org/3/whatsnew/3.13.html#defined-mutation-semantics-for-locals
https://github.com/python/cpython/blob/v3.13.6-32-g3a74d52584c/Objects/frameobject.c#L161-L176

-> Fix that by explicitly testing for that FrameLocalsProxy and not
trying to invoke del on that. We anyway whiteout "fast locals" manually,
so that should work.

/reviewed-by @jerome
/reviewed-on https://lab.nexedi.com/nexedi/pygolang/-/merge_requests/37