pyx.build: Runtime-patch Cython 3 so that `cdef ... except +topyexc` is allowed
Cython 3 was released in 2023 and made (one of several) backward
incompatible change: non-extern cdef functions can no longer throw C++
exceptions. This manifests itself as e.g.

    cdef nogil:

        _chan* _makechan_pyexc(unsigned elemsize, unsigned size)    except +topyexc:
        ^
    ------------------------------------------------------------

    golang/_golang.pyx:578:4: Only extern functions can throw C++ exceptions.

and breaks the build for both pygolang and wendelin.core .

To fix the build we pinned 'Cython < 3' in 6446a0be (pyx.build: Fix
build after Cython 3 release) at that time.

I further talked to Cython upstream trying to explain why pygolang needs such
`cdef ... except +topyexc` functions and why this need is unconditional:

    https://github.com/cython/cython/issues/5981#issuecomment-2143821302
    https://github.com/cython/cython/issues/5981#issuecomment-3148459989
    https://github.com/cython/cython/issues/5981#issuecomment-3151826667
    ...

However there is no sign that upstream is interested to fix this timely
and my understanding is that they are ok with the breakage.

We used to live with Cython 0.29.x just ok, but that version of Cython
only supports Python ≤ 3.12 and breaks with Python 3.13 even on simple
test module (see appendix for details). So in order to provide py3.13
support support for Cython 3 needs to be worked out.

-> Provide that Cython3 support in the form of runtime patch.

It seems we can hook into the build process and adjust the logic to
allow `cdef ... except +topyexc`. The main upstream concern against that,
that was the reason to deactivate the feature, was that the current
Cython codegeneration infrastructure does not handle the `except
+topyexc` logic correctly when there are reference-counted variables
inside the function. We stay safe and allow `cdef ... except +topyexc`
only for functions that do not have refcounted variables inside. Please
see added comments in golang/pyx/build.py for details.

After this patch pygolang can now be build ok with both Cython 0.29.x
and Cython 3.

Appendix. Proof that Cython < 3 does not work with Python 3.13
--------------------------------------------------------------

from https://lab.nexedi.com/nexedi/slapos/-/merge_requests/1863#note_241592:

    kirr@deca:~/tmp/trashme/cy$ python3.13 -m venv 1.venv

    kirr@deca:~/tmp/trashme/cy$ . 1.venv/bin/activate

    (1.venv) kirr@deca:~/tmp/trashme/cy$ pip install 'cython < 3'
    Collecting cython<3
      Using cached Cython-0.29.37-py2.py3-none-any.whl.metadata (3.1 kB)
    Using cached Cython-0.29.37-py2.py3-none-any.whl (989 kB)
    Installing collected packages: cython
    Successfully installed cython-0.29.37

    (1.venv) kirr@deca:~/tmp/trashme/cy$ cat >x.pyx
    print('hello')

    (1.venv) kirr@deca:~/tmp/trashme/cy$ pip install setuptools
    Collecting setuptools
      Using cached setuptools-80.9.0-py3-none-any.whl.metadata (6.6 kB)
    Using cached setuptools-80.9.0-py3-none-any.whl (1.2 MB)
    Installing collected packages: setuptools
    Successfully installed setuptools-80.9.0

    (1.venv) kirr@deca:~/tmp/trashme/cy$ cythonize -i x.pyx
    Compiling /home/kirr/tmp/trashme/cy/x.pyx because it changed.
    [1/1] Cythonizing /home/kirr/tmp/trashme/cy/x.pyx
    /home/kirr/tmp/trashme/cy/1.venv/lib/python3.13/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/kirr/tmp/trashme/cy/x.pyx
      tree = Parsing.p_module(s, pxd, full_module_name)
    /home/kirr/tmp/trashme/cy/x.c:840:1: warning: ‘Py_UNICODE’ is deprecated [-Wdeprecated-declarations]
      840 | static CYTHON_INLINE size_t __Pyx_Py_UNICODE_strlen(const Py_UNICODE *u) {
          | ^~~~~~
    /home/kirr/tmp/trashme/cy/x.c: In function ‘__Pyx_Py_UNICODE_strlen’:
    /home/kirr/tmp/trashme/cy/x.c:841:5: warning: ‘Py_UNICODE’ is deprecated [-Wdeprecated-declarations]
      841 |     const Py_UNICODE *u_end = u;
          |     ^~~~~
    /home/kirr/tmp/trashme/cy/x.c: In function ‘__Pyx_PyInt_As_long’:
    /home/kirr/tmp/trashme/cy/x.c:2256:27: error: too few arguments to function ‘_PyLong_AsByteArray’
     2256 |                 int ret = _PyLong_AsByteArray((PyLongObject *)v,
          |                           ^~~~~~~~~~~~~~~~~~~
    In file included from /usr/include/python3.13/longobject.h:107,
                     from /usr/include/python3.13/Python.h:81,
                     from /home/kirr/tmp/trashme/cy/x.c:18:
    /usr/include/python3.13/cpython/longobject.h:111:17: note: declared here
      111 | PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,
          |                 ^~~~~~~~~~~~~~~~~~~
    /home/kirr/tmp/trashme/cy/x.c: In function ‘__Pyx_PyInt_As_int’:
    /home/kirr/tmp/trashme/cy/x.c:2452:27: error: too few arguments to function ‘_PyLong_AsByteArray’
     2452 |                 int ret = _PyLong_AsByteArray((PyLongObject *)v,
          |                           ^~~~~~~~~~~~~~~~~~~
    /usr/include/python3.13/cpython/longobject.h:111:17: note: declared here
      111 | PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,
          |                 ^~~~~~~~~~~~~~~~~~~
    error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1

/reviewed-by @jerome
/reviewed-on https://lab.nexedi.com/nexedi/pygolang/-/merge_requests/37