golang: Fix XPyFrame_WhiteoutFastLocal for py3.14
Problem 1:

    golang/_golang.cpp: In function ‘void XPyFrame_WhiteoutFastLocal(PyFrameObject*, PyObject*)’:
    golang/_golang.cpp:1572:43: error: invalid use of incomplete type ‘_PyInterpreterFrame’ {aka ‘struct _PyInterpreterFrame’}
     1572 |                                 f->f_frame->localsplus;
          |                                           ^~
    In file included from /home/kirr/local/py3.14/include/python3.14/pyframe.h:19,
                     from /home/kirr/local/py3.14/include/python3.14/Python.h:113,
                     from golang/_golang.cpp:150:
    /home/kirr/local/py3.14/include/python3.14/cpython/pyframe.h:25:8: note: forward declaration of ‘_PyInterpreterFrame’ {aka ‘struct _PyInterpreterFrame’}
       25 | struct _PyInterpreterFrame;
          |        ^~~~~~~~~~~~~~~~~~~

-> include internal/pycore_interpframe.h like we already do with e.g. internal/pycore_frame.h .

Problem 2:

    golang/_golang.cpp: In function ‘void XPyFrame_WhiteoutFastLocal(PyFrameObject*, PyObject*)’:
    golang/_golang.cpp:1575:45: error: cannot convert ‘_PyStackRef*’ to ‘PyObject**’ {aka ‘_object**’} in initialization
     1575 |                                 f->f_frame->localsplus;
          |                                 ~~~~~~~~~~~~^~~~~~~~~~
          |                                             |
          |                                             _PyStackRef*

It turns out _PyInterpreterFrame.localsplus was changed from PyObject to _PyStackRef:

    https://github.com/python/cpython/commit/22b0de2755ee2
    https://github.com/python/cpython/pull/118450
    https://github.com/python/cpython/issues/117139

-> Adjust the code to work with localsplus as _PyStackRef on py3.14+ .

/reviewed-by @jerome
/reviewed-on https://lab.nexedi.com/nexedi/pygolang/-/merge_requests/39