*: NULL -> nil (Pyx and only where we can)
Convert Pyx part of the project to use nil instead of NULL.

Not every usage of NULL was converted and some places were left to use
NULL where changing it to nil currently hits Cython compilation error:

https://github.com/cython/cython/issues/3314