golang_str: tests: Adjust _DeepReplacer for py3.14
There is no copy._deepcopy_atomic on py3.14:

    r = <golang.golang_str_test._DeepReplacer object at 0x7f1d576812b0>, obj = ('α',)

        def _replace(r, obj):
            if r.fpred(obj):
                return r.freplace(obj)

            cls = type(obj)
            if issubclass(cls, type): # a class, e.g. 'tuple'
                return obj
            # fast path for atomic objects (int, float, bool, bytes, unicode, ... but not e.g. tuple)
    >       if copy._deepcopy_dispatch.get(cls) is copy._deepcopy_atomic:
                                                   ^^^^^^^^^^^^^^^^^^^^^
    E       AttributeError: module 'copy' has no attribute '_deepcopy_atomic'. Did you mean: '_deepcopy_dict'?

    golang/golang_str_test.py:2208: AttributeError

it was converted to copy._atomic_types in https://github.com/python/cpython/commit/9d6604222e9e .

-> Adjust the code to use that on py3.14+ .

/reviewed-by @jerome
/reviewed-on https://lab.nexedi.com/nexedi/pygolang/-/merge_requests/39